name: "resolve-deps"
version: "2.0.0"
usage: "Resolve local and remote dependencies in a proper, fast, concurrent way"
command: "$HELM_PLUGIN_DIR/bin/resolve-deps"
useTunnel: false
ignoreFlags: false
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
  upgrade: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"